# Generated by Django 5.2.5 on 2025-08-18 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_tag', models.CharField(blank=True, choices=[('high_priority', 'High Priority'), ('reviewed', 'Reviewed'), ('escalated', 'Escalated'), ('false_positive', 'False Positive'), ('pending_action', 'Pending Action'), ('legal_review', 'Legal Review'), ('duplicate', 'Duplicate Report')], help_text='Moderation categorization tag', max_length=30)),
                ('report_type', models.CharField(choices=[('bug', 'Bug Report'), ('spam', 'Spam'), ('scam', 'Scam'), ('harm', 'Harmful Content'), ('graphic', 'Inappropriate Content'), ('privacy', 'Privacy Violation'), ('copyright', 'Copyright Issues'), ('duplicate', 'Duplicate Content'), ('plagiarism', 'Plagiarized Research')], help_text='Type of issue to report', max_length=35)),
                ('report_title', models.CharField(max_length=256)),
                ('reason', models.TextField(max_length=8000)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
