# Generated by Django 5.2.5 on 2025-08-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_report', '0002_rename_created_reportmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='report_tag',
            field=models.CharField(blank=True, choices=[('reviewed', 'Reviewed'), ('duplicate', 'Duplicate Report'), ('escalated', 'Escalated'), ('legal_review', 'Legal Review'), ('high_priority', 'High Priority'), ('false_positive', 'False Positive'), ('pending_action', 'Pending Action')], help_text='Moderation categorization tag', max_length=30),
        ),
    ]
