# Generated by Django 5.2.5 on 2025-08-18 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines_process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(max_length=512)),
                ('key', models.CharField(max_length=64)),
                ('value', models.TextField()),
                ('value_type', models.CharField(max_length=64)),
                ('default_value', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('originated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_parameter', to='pipelines_parameter.parametermodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameter_owner', to=settings.AUTH_USER_MODEL)),
                ('processes', models.ManyToManyField(related_name='parameter_processes', to='pipelines_process.processmodel')),
            ],
            options={
                'verbose_name_plural': 'Parameters',
                'db_table': 'pipelines_parameter',
                'ordering': ['-created_at'],
            },
        ),
    ]
