# Generated by Django 5.2.5 on 2025-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines_parameter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametermodel',
            name='originated_from',
        ),
        migrations.RemoveField(
            model_name='parametermodel',
            name='owner',
        ),
        migrations.AddField(
            model_name='parametermodel',
            name='version_history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
