# Generated by Django 5.2.5 on 2025-08-20 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines_parameter', '0002_remove_parametermodel_originated_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parametermodel',
            name='originated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_%(class)s', to='pipelines_parameter.parametermodel'),
        ),
        migrations.AddField(
            model_name='parametermodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
