# Generated by Django 5.2.5 on 2025-08-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines_parameter', '0003_parametermodel_originated_from_parametermodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametermodel',
            name='processes',
        ),
    ]
