# Generated by Django 5.2.5 on 2025-08-25 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines_parameter', '0004_remove_parametermodel_processes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermodel',
            name='originated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_%(class)s', to='pipelines_parameter.parametermodel'),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
