# Generated by Django 5.2.5 on 2025-08-18 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmplifyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('content', models.TextField(blank=True, max_length=8000)),
                ('amplified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amplifies_created', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'forums_amplify',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='forums_ampl_content_88e817_idx'), models.Index(fields=['amplified_by'], name='forums_ampl_amplifi_c35b09_idx')],
                'unique_together': {('amplified_by', 'content_type', 'object_id')},
            },
        ),
    ]
