# Generated by Django 5.2.5 on 2025-08-27 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forums_amplify', '0003_amplifymodel_last_edited_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amplifymodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='amplifymodel',
            name='is_content_preserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amplifymodel',
            name='original_post_author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='amplifymodel',
            name='original_post_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amplifymodel',
            name='original_post_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amplifymodel',
            name='original_post_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='amplifymodel',
            index=models.Index(fields=['is_content_preserved'], name='forums_ampl_is_cont_238550_idx'),
        ),
    ]
