# Generated by Django 5.2.4 on 2025-07-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_thing', models.CharField(max_length=15)),
                ('last_thing', models.CharField(max_length=30)),
            ],
        ),
    ]
