# Generated by Django 5.2.5 on 2025-08-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums_like', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likemodel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='likemodel',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
