# Generated by Django 5.2.5 on 2025-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_opine', '0002_rename_created_opinemodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinemodel',
            name='edited',
        ),
        migrations.AddField(
            model_name='opinemodel',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, help_text='When this item was last edited by a user (not system updates)', null=True),
        ),
    ]
