# Generated by Django 5.2.5 on 2025-08-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums_opine', '0003_remove_opinemodel_edited_opinemodel_last_edited_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opinemodel',
            unique_together=set(),
        ),
    ]
