# Generated by Django 5.2.5 on 2025-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines_process', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processmodel',
            name='originated_from',
        ),
        migrations.RemoveField(
            model_name='processmodel',
            name='owner',
        ),
        migrations.AddField(
            model_name='processmodel',
            name='version_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='processmodel',
            name='version',
            field=models.CharField(default='0.0.1', max_length=64),
        ),
    ]
