# Generated by Django 5.2.5 on 2025-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines_parameter', '0004_remove_parametermodel_processes'),
        ('pipelines_process', '0003_processmodel_originated_from_processmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmodel',
            name='parameters',
            field=models.ManyToManyField(related_name='processes', to='pipelines_parameter.parametermodel'),
        ),
    ]
