# Generated by Django 5.2.5 on 2025-09-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines_process', '0005_alter_processmodel_originated_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmodel',
            name='inputs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='processmodel',
            name='outputs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
