# Generated by Django 5.2.5 on 2025-08-18 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums_announce', '0002_rename_created_announcemodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcemodel',
            name='edited',
        ),
    ]
