# Generated by Django 5.2.4 on 2025-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, null=True)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('bio', models.TextField(blank=True, null=True)),
                ('orcid', models.CharField(blank=True, null=True)),
                ('university', models.CharField(blank=True, null=True)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
