# Generated by Django 5.2.5 on 2025-08-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forums_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbfusermodel',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='wbfusermodel',
            name='github_profile',
            field=models.URLField(blank=True, help_text='Link to Github user account'),
        ),
        migrations.AddField(
            model_name='wbfusermodel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wbfusermodel',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='Link to linkedin profile'),
        ),
        migrations.AddField(
            model_name='wbfusermodel',
            name='twitter_profile',
            field=models.URLField(blank=True, help_text='Link to twitter/x account'),
        ),
        migrations.AddField(
            model_name='wbfusermodel',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or lab website'),
        ),
        migrations.AlterField(
            model_name='wbfusermodel',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short biography', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wbfusermodel',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wbfusermodel',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wbfusermodel',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wbfusermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='wbf_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='wbfusermodel',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wbfusermodel',
            name='orcid',
            field=models.CharField(blank=True, default='', help_text='ORCID ID (0000-0000-0000-0000)', max_length=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wbfusermodel',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wbfusermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='wbf_users', to='auth.permission'),
        ),
    ]
