# Generated by Django 5.2.5 on 2025-08-18 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_user', '0002_remove_wbfusermodel_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbfusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
