# Generated by Django 5.2.5 on 2025-08-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_user', '0003_wbfusermodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbfusermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
