# Generated by Django 5.2.5 on 2025-08-25 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_user', '0004_wbfusermodel_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_notifications_enabled', models.BooleanField(default=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forums_user_follow',
                'indexes': [models.Index(fields=['follower'], name='forums_user_followe_3dcbb3_idx'), models.Index(fields=['following'], name='forums_user_followi_639a89_idx'), models.Index(fields=['created_at'], name='forums_user_created_55f9be_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
