# Generated by Django 5.2.5 on 2025-08-18 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines_process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pipeline_title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=16000)),
                ('version', models.CharField(default='0.0.1a', max_length=64)),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_data', models.JSONField(default=dict, help_text='ReactFlow nodes and edges data')),
                ('originated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_pipeline', to='pipelines_pipeline.pipelinemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_owner', to=settings.AUTH_USER_MODEL)),
                ('processes', models.ManyToManyField(related_name='pipelines', to='pipelines_process.processmodel')),
            ],
            options={
                'verbose_name_plural': 'Pipelines',
                'db_table': 'pipelines_pipeline',
                'ordering': ['-created_at'],
            },
        ),
    ]
